<?php

/**
 * @file
 * Contains brand.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function brand_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the brand module.
    case 'help.page.brand':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Brand manipulation') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function brand_theme() {
  $theme = [];

  return $theme;
}
